Repository Ca-moes/ServerClientWC, pull requests merged in 2020-04, with the labels that each got.

#15 Bash e Makefiles
  run.bash
  src/Q1server.c
  src/U1client.c
  src/makefile.Q1
  src/makefile.U1
Labels: enhancement

#16 Make client
  src/Q1server.c
  src/U1client.c
Labels: Qn, Un

#18 Threads
  removefifo.bash
  run.bash
  src/Q1.c
  src/U1.c
  src/makefile
Labels: Qn

#19 começo mensagens
  run.bash
  src/Q1.c
  src/U1.c
  src/registers.c
  src/registers.h
Labels: Qn, Un
